### ISSUE TITLE
Dojo de git e gitflow

### ISSUE THREAD

**Issue by joao15victor08** [fga-eps-mds/2023.2-UnB-TV-DOC#2]
## Descrição
Realizar Dojo sobre git e gitflow com os membros de MDS

## Critérios de Aceitação:
- [x] Dojo realizado

## Informações Adicionais

Data de realização: 18/09

**Comment by joao15victor08** [comment]
Dojo realizado das 20h as 20h40.
Membros de MDS presentes: Todos.
Membros de EPS: João Victor, Gabrielle e Lucas

**Comment by Gabrielle-Ribeiro** [comment]
Link da gravação: https://youtu.be/mFeM3cqw0o4
