### ISSUE TITLE
Dojo de Angular

### ISSUE THREAD

**Issue by DaviMarinho** [fga-eps-mds/2023.2-UnB-TV-DOC#4]
## Descrição
Realizar Dojo sobre Angular com os membros de MDS e EPS

## Critérios de Aceitação:
- [x] Dojo realizado

## Informações Adicionais

Data de realização: 20/09

**Comment by Gabrielle-Ribeiro** [comment]
Link da gravação: https://youtu.be/hVNFkhu_1G4
