### ISSUE TITLE
US-12 - Eu, como usuário, desejo ter a opção de compartilhar um vídeo a fim de ser capaz de divulgar um conteúdo para conhecidos 

### ISSUE THREAD

**Issue by eric-kingu** [fga-eps-mds/2023.2-UnB-TV-DOC#61]
## Descrição
Eu, como usuário, desejo ter a opção de compartilhar um vídeo a fim de ser capaz de divulgar um conteúdo para conhecidos 

## Critérios de Aceitação:
- [ ] Usuário deve poder compartilhar um vídeo

## Informações Adicionais

Aqui informações adicionais

**Comment by joao15victor08** [comment]
Issue repetida
