### ISSUE TITLE
Template de Issues e PRs

### ISSUE THREAD

**Issue by DaviMarinho** [fga-eps-mds/2023.2-UnB-TV-DOC#7]
## Descrição
Criar um template nos repositórios de Frontend, Backend e de documentação para Issues e PRs.

## Critérios de Aceitação:
- [x] Criar template de Issues no repositório Docs.
- [x] Criar template de PRs no repositório Docs.
- [x] Criar template de PRs no repositório Frontend.
- [x] Criar template de Issues no repositório Frontend.
- [x] Criar template de PRs no repositório Backend.
- [x] Criar template de Issues no repositório Backend.
## Informações Adicionais

**Comment by geraldovictor** [comment]
Template de issue já está pronto
