### ISSUE TITLE
Iniciar repositório de Backend

### ISSUE THREAD

**Issue by DaviMarinho** [fga-eps-mds/2023.2-UnB-TV-DOC#9]
## Descrição
Iniciar o repositório do Backend.

## Critérios de Aceitação:
- [ ] Inicializar o repositório no Github.
- [ ] Fazer o primeiro commit já com a tecnologia escolhida pelo time.

## Informações Adicionais

**Comment by joao15victor08** [comment]
Repositório criado: https://github.com/fga-eps-mds/2023.2-UnB-TV-Users
